# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean install'

- task: Docker@2
  displayName: 'Docker Build'
  inputs:
    command: 'build'
    containerRegistry: 'DOCKER_ACR_PUSH'
    repository: 'springboot'
    Dockerfile: '$(System.DefaultWorkingDirectory)/Dockerfile'
    tags: 'np000'

- task: Docker@2
  displayName: 'Docker Push'
  inputs:
    containerRegistry: 'DOCKER_ACR_PUSH'
    repository: 'springboot'
    command: 'push'
    tags: 'np000'